DOLLS = [
    {
        'slug': 'draculaura',
        'name': 'Draculaura',
        'image': 'img/doll1.webp',
        'description': 'Базовая Дракулаура Generation 1.',
        'year': 2010,
        'price': 4500,
    },
    {
        'slug': 'frankie-stein',
        'name': 'Frankie Stein',
        'image': 'img/doll2.webp',
        'description': 'Яркая коллекционная кукла.',
        'year': 2010,
        'price': 4700,
    },
    {
        'slug': 'clawdeen-wolf',
        'name': 'Clawdeen Wolf',
        'image': 'img/doll3.webp',
        'description': 'Базовая Клодин Generation 1.',
        'year': 2010,
        'price': 4600,
    },
    {
        'slug': 'lagoona-blue',
        'name': 'Lagoona Blue',
        'image': 'img/doll4.webp',
        'description': 'Базовая Лагуна Generation 1.',
        'year': 2010,
        'price': 4400,
    },
    {
        'slug': 'cleo-de-nile-and-deuce-gorgon',
        'name': 'Cleo de Nile and Deuce Gorgon',
        'image': 'img/doll5.webp',
        'description': 'Парная кукла Generation 1.',
        'year': 2010,
        'price': 6800,
    },
    {
        'slug': 'ghoulia-yelps',
        'name': 'Ghoulia Yelps',
        'image': 'img/doll6.webp',
        'description': 'Базовая Гулия Generation 1.',
        'year': 2010,
        'price': 4300,
    },
    {
        'slug': 'draculaura-gloom-beach',
        'name': 'Draculaura',
        'image': 'img/doll7.webp',
        'description': 'Gloom Beach Дракулаура Generation 1.',
        'year': 2010,
        'price': 3900,
    },
    {
        'slug': 'frankie-stein-gloom-beach',
        'name': 'Frankie Stein',
        'image': 'img/doll8.webp',
        'description': 'Gloom Beach Френки Generation 1.',
        'year': 2010,
        'price': 3700,
    },
    {
        'slug': 'clawdeen-wolf-gloom-beach',
        'name': 'Clawdeen Wolf',
        'image': 'img/doll9.webp',
        'description': 'Gloom Beach Клодин Generation 1.',
        'year': 2010,
        'price': 3800,
    },
    {
        'slug': 'cleo-de-nile-gloom-beach',
        'name': 'Cleo de Nile',
        'image': 'img/doll10.webp',
        'description': 'Gloom Beach Клео Generation 1.',
        'year': 2010,
        'price': 4000,
    },
    {
        'slug': 'draculaura-dead-tired',
        'name': 'Draculaura',
        'image': 'img/doll11.webp',
        'description': 'Dead Tired Дракулаура Generation 1.',
        'year': 2011,
        'price': 4500,
    },
    {
        'slug': 'frankie-stein-dead-tired',
        'name': 'Frankie Stein',
        'image': 'img/doll12.webp',
        'description': 'Dead Tired Френки Generation 1.',
        'year': 2011,
        'price': 4300,
    },
    {
        'slug': 'cleo-de-nile-dead-tired',
        'name': 'Cleo de Nile',
        'image': 'img/doll14.webp',
        'description': 'Dead Tired Клео Generation 1.',
        'year': 2011,
        'price': 4400,
    },
    {
        'slug': 'lagoona-blue-dead-tired',
        'name': 'Lagoona Blue',
        'image': 'img/doll13.webp',
        'description': 'Dead Tired Лагуна Generation 1.',
        'year': 2011,
        'price': 5100,
    },
    {
        'slug': 'ghoulia-yelps-dead-tired',
        'name': 'Ghoulia Yelps',
        'image': 'img/doll15.webp',
        'description': 'Dead Tired Гулия Generation 1.',
        'year': 2011,
        'price': 4300,
    },
]